package de.htwg.sa.nmm.persistence.hibernate;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import de.htwg.sa.nmm.model.IPlayer;
import de.htwg.sa.nmm.model.IPlayer.Status;
import de.htwg.sa.nmm.model.IToken;
import de.htwg.sa.nmm.model.impl.Player;

/**
 * {@link Player} class with Hibernate annotations
 * 
 * @author Patrick Schmidt
 * @since 2016-04-05
 */
@Entity
@Table(name = "Hibernate_TEST5")
public class HibernatePlayer implements Serializable {

	/**
	 * Serial Version ID
	 */
	private static final long serialVersionUID = -1428233773590215096L;

	/**
	 * Autogenerated Id for Hibernate
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private int id;

	/**
	 * Name of the player
	 */
	@Column(name = "playername")
	String name = "";

	/**
	 * Tokencolor
	 */
	@Column(name = "color")
	IToken.Color color = null;

	/**
	 * Status of the player
	 */
	@Column(name = "status")
	Status status;

	/**
	 * Number of tokens player can place
	 */
	@Column(name = "token")
	int token;

	@OneToOne
	HibernateGamefield game;

	static HibernatePlayer transformToHibernate(IPlayer player) {
		HibernatePlayer p = new HibernatePlayer();

		p.name = player.name();
		p.color = player.color();
		p.status = player.getStatus();
		p.token = player.token();

		return p;
	}

	static IPlayer transformFromHibernate(HibernatePlayer player) {
		Player p = new Player(player.name, player.color);

		p.setStatus(player.status);
		p.setToken(player.token);

		return p;
	}

	// ##### Getter/setter Methods ####

	public HibernatePlayer() {
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public IToken.Color getColor() {
		return color;
	}

	public void setColor(IToken.Color color) {
		this.color = color;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public int getToken() {
		return token;
	}

	public void setToken(int token) {
		this.token = token;
	}

	public HibernateGamefield getGame() {
		return game;
	}

	public void setGame(HibernateGamefield game) {
		this.game = game;
	}

}