package de.htwg.sa.nmm.persistence.hibernate;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import de.htwg.sa.nmm.model.IField;
import de.htwg.sa.nmm.model.IGamefield;
import de.htwg.sa.nmm.model.IPlayer;
import de.htwg.sa.nmm.model.impl.Field;
import de.htwg.sa.nmm.model.impl.Gamefield;

/**
 * {@link Gamefield} class with Hibernate Annotations
 * 
 * @author Patrick Schmidt
 * @since 2016-04-05
 */
@Entity
@Table(name = "Hibernate_TEST1")
public class HibernateGamefield implements Serializable {

	/**
	 * Serial Version ID
	 */
	private static final long serialVersionUID = 6474755332679443051L;

	/**
	 * Autogenerated Id for Hibernate
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private int id;

	/**
	 * Name of the Game.
	 */
	@Column(name = "name")
	private String name = "";

	/**
	 * Field matrix to address the specific positions
	 */
	@OneToMany(mappedBy = "game")
	private List<HibernateMatrixRow> rows = new ArrayList<>();

	/**
	 * Variable to store player1
	 */
	@OneToOne(mappedBy = "game")
	private HibernatePlayer player1;

	/**
	 * Variable to store player2
	 */
	@OneToOne(mappedBy = "game")
	private HibernatePlayer player2;

	public static HibernateGamefield transformToHibernate(IGamefield gamefield) {
		HibernateGamefield game = new HibernateGamefield();

		game.name = gamefield.getName();
		game.player1 = HibernatePlayer.transformToHibernate(gamefield.getCurrentPlayer());
		game.player2 = HibernatePlayer.transformToHibernate(gamefield.getOtherPlayer());

		IField[][] field = gamefield.getGamefield();
		HibernateMatrixRow mr;
		for (int g = 0; g < gamefield.grids(); g++) {
			mr = new HibernateMatrixRow();
			for (int i = 0; i < gamefield.index(); i++) {
				mr.row.add(HibernateField.transformToHibernate(field[g][i]));
			}
			game.rows.add(mr);
		}

		return game;
	}

	public static IGamefield transformFromHibernate(HibernateGamefield gamefield) {
		IPlayer p1 = HibernatePlayer.transformFromHibernate(gamefield.player1);
		IPlayer p2 = HibernatePlayer.transformFromHibernate(gamefield.player2);

		IGamefield game = new Gamefield(p1, p2);

		game.setName(gamefield.name);

		IField[][] field = new Field[game.grids()][game.index()];
		for (int g = 0; g < game.grids(); g++) {
			for (int i = 0; i < game.index(); i++) {
				field[g][i] = HibernateField.transformFromHibernate(gamefield.rows.get(g).row.get(i));
			}
		}
		game.setGamefield(field);

		return game;
	}
	
	// ##### Getter/setter Methods ####

	public HibernateGamefield() {

	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<HibernateMatrixRow> getRows() {
		return rows;
	}

	public void setRows(List<HibernateMatrixRow> rows) {
		this.rows = rows;
	}

	public HibernatePlayer getPlayer1() {
		return player1;
	}

	public void setPlayer1(HibernatePlayer player1) {
		this.player1 = player1;
	}

	public HibernatePlayer getPlayer2() {
		return player2;
	}

	public void setPlayer2(HibernatePlayer player2) {
		this.player2 = player2;
	}
	
}
