package de.htwg.sa.nmm.persistence.hibernate;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import de.htwg.sa.nmm.model.IPlayer;
import de.htwg.sa.nmm.model.impl.Field;
import de.htwg.sa.nmm.model.impl.Gamefield;
import de.htwg.sa.nmm.model.impl.Player;

/**
 * {@link Gamefield} class with Hibernate Annotations
 * 
 * @author Patrick Schmidt
 * @since 2016-04-05
 */
public class HibernateGamefield implements Serializable{

	/**
	 * Serial Version ID
	 */
	private static final long serialVersionUID = 6474755332679443051L;

	/**
	 * Autogenerated Id for Hibernate
	 */
	@Id
	@GeneratedValue
	@Column(name = "id")
	private int id;

	/**
	 * Name of the Game. Needed to identify the game in db4o database
	 */
	@Column(name = "name")
	private String name = "";
	
	/**
	 * Field matrix to address the specific positions
	 */
	@Column(name = "field")
	private Field[][] gamefield = null;
	

	/**
	 * Variable to store player1
	 */
	@OneToOne(targetEntity = Player.class)
	@JoinColumn(name = "player_one")
	private IPlayer player1;

	/**
	 * Variable to store player2
	 */
	@OneToOne(targetEntity = Player.class)
	@JoinColumn(name = "player_two")
	private IPlayer player2;

	/**
	 * Variable to store the current player
	 */
	@OneToOne(targetEntity = Player.class)
	@JoinColumn(name = "current_player")
	private IPlayer currentPlayer;

	/**
	 * Default Constructor for Hibernate
	 */
	protected HibernateGamefield() {
		// do nothing just for Hibernate
	}
	
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Field[][] getGamefield() {
		return gamefield;
	}

	public void setGamefield(Field[][] gamefield) {
		this.gamefield = gamefield;
	}

	public IPlayer getPlayer1() {
		return player1;
	}

	public void setPlayer1(IPlayer player1) {
		this.player1 = player1;
	}

	public IPlayer getPlayer2() {
		return player2;
	}

	public void setPlayer2(IPlayer player2) {
		this.player2 = player2;
	}

	public IPlayer getCurrentPlayer() {
		return currentPlayer;
	}

	public void setCurrentPlayer(IPlayer currentPlayer) {
		this.currentPlayer = currentPlayer;
	}

}
